import typing, abc
from System import Array_1
from RobloxFiles.Enums import RotationOrder, ContentSourceType, FontWeight, FontStyle, Font, Material, Axis, NormalId
from RobloxFiles import RbxObject

class Axes(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    X : Axes # 1
    Y : Axes # 2
    Z : Axes # 4


class BrickColor:
    Color : Color3
    Id : BrickColorId
    Name : str
    @property
    def B(self) -> float: ...
    @property
    def G(self) -> float: ...
    @property
    def Number(self) -> int: ...
    @property
    def R(self) -> float: ...
    @staticmethod
    def Black() -> BrickColor: ...
    @staticmethod
    def Blue() -> BrickColor: ...
    @staticmethod
    def DarkGray() -> BrickColor: ...
    def Equals(self, obj: typing.Any) -> bool: ...
    @staticmethod
    def FromColor3(color: Color3) -> BrickColor: ...
    @staticmethod
    def FromName(name: str) -> BrickColor: ...
    @staticmethod
    def FromNumber(number: int) -> BrickColor: ...
    @staticmethod
    def FromRGB(r: float = ..., g: float = ..., b: float = ...) -> BrickColor: ...
    def GetHashCode(self) -> int: ...
    @staticmethod
    def Gray() -> BrickColor: ...
    @staticmethod
    def Green() -> BrickColor: ...
    # Operator not supported op_Implicit(number: Int32)
    # Operator not supported op_Implicit(id: BrickColorId)
    # Operator not supported op_Implicit(color: BrickColor)
    # Operator not supported op_Implicit(color: BrickColor)
    @staticmethod
    def Palette(index: int) -> BrickColor: ...
    @staticmethod
    def Random() -> BrickColor: ...
    @staticmethod
    def Red() -> BrickColor: ...
    def ToString(self) -> str: ...
    @staticmethod
    def White() -> BrickColor: ...
    @staticmethod
    def Yellow() -> BrickColor: ...


class BrickColorId(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    White : BrickColorId # 1
    Grey : BrickColorId # 2
    Light_yellow : BrickColorId # 3
    Brick_yellow : BrickColorId # 5
    Light_green_Mint : BrickColorId # 6
    Light_reddish_violet : BrickColorId # 9
    Pastel_Blue : BrickColorId # 11
    Light_orange_brown : BrickColorId # 12
    Nougat : BrickColorId # 18
    Bright_red : BrickColorId # 21
    Med_reddish_violet : BrickColorId # 22
    Bright_blue : BrickColorId # 23
    Bright_yellow : BrickColorId # 24
    Earth_orange : BrickColorId # 25
    Black : BrickColorId # 26
    Dark_grey : BrickColorId # 27
    Dark_green : BrickColorId # 28
    Medium_green : BrickColorId # 29
    Lig_Yellowich_orange : BrickColorId # 36
    Bright_green : BrickColorId # 37
    Dark_orange : BrickColorId # 38
    Light_bluish_violet : BrickColorId # 39
    Transparent : BrickColorId # 40
    Tr_Red : BrickColorId # 41
    Tr_Lg_blue : BrickColorId # 42
    Tr_Blue : BrickColorId # 43
    Tr_Yellow : BrickColorId # 44
    Light_blue : BrickColorId # 45
    Tr_Flu_Reddish_orange : BrickColorId # 47
    Tr_Green : BrickColorId # 48
    Tr_Flu_Green : BrickColorId # 49
    Phosph_White : BrickColorId # 50
    Light_red : BrickColorId # 100
    Medium_red : BrickColorId # 101
    Medium_blue : BrickColorId # 102
    Light_grey : BrickColorId # 103
    Bright_violet : BrickColorId # 104
    Br_yellowish_orange : BrickColorId # 105
    Bright_orange : BrickColorId # 106
    Bright_bluish_green : BrickColorId # 107
    Earth_yellow : BrickColorId # 108
    Bright_bluish_violet : BrickColorId # 110
    Tr_Brown : BrickColorId # 111
    Medium_bluish_violet : BrickColorId # 112
    Tr_Medi_reddish_violet : BrickColorId # 113
    Med_yellowish_green : BrickColorId # 115
    Med_bluish_green : BrickColorId # 116
    Light_bluish_green : BrickColorId # 118
    Br_yellowish_green : BrickColorId # 119
    Lig_yellowish_green : BrickColorId # 120
    Med_yellowish_orange : BrickColorId # 121
    Br_reddish_orange : BrickColorId # 123
    Bright_reddish_violet : BrickColorId # 124
    Light_orange : BrickColorId # 125
    Tr_Bright_bluish_violet : BrickColorId # 126
    Gold : BrickColorId # 127
    Dark_nougat : BrickColorId # 128
    Silver : BrickColorId # 131
    Neon_orange : BrickColorId # 133
    Neon_green : BrickColorId # 134
    Sand_blue : BrickColorId # 135
    Sand_violet : BrickColorId # 136
    Medium_orange : BrickColorId # 137
    Sand_yellow : BrickColorId # 138
    Earth_blue : BrickColorId # 140
    Earth_green : BrickColorId # 141
    Tr_Flu_Blue : BrickColorId # 143
    Sand_blue_metallic : BrickColorId # 145
    Sand_violet_metallic : BrickColorId # 146
    Sand_yellow_metallic : BrickColorId # 147
    Dark_grey_metallic : BrickColorId # 148
    Black_metallic : BrickColorId # 149
    Light_grey_metallic : BrickColorId # 150
    Sand_green : BrickColorId # 151
    Sand_red : BrickColorId # 153
    Dark_red : BrickColorId # 154
    Tr_Flu_Yellow : BrickColorId # 157
    Tr_Flu_Red : BrickColorId # 158
    Gun_metallic : BrickColorId # 168
    Red_flipflop : BrickColorId # 176
    Yellow_flipflop : BrickColorId # 178
    Silver_flipflop : BrickColorId # 179
    Curry : BrickColorId # 180
    Fire_Yellow : BrickColorId # 190
    Flame_yellowish_orange : BrickColorId # 191
    Reddish_brown : BrickColorId # 192
    Flame_reddish_orange : BrickColorId # 193
    Medium_stone_grey : BrickColorId # 194
    Royal_blue : BrickColorId # 195
    Dark_Royal_blue : BrickColorId # 196
    Bright_reddish_lilac : BrickColorId # 198
    Dark_stone_grey : BrickColorId # 199
    Lemon_metalic : BrickColorId # 200
    Light_stone_grey : BrickColorId # 208
    Dark_Curry : BrickColorId # 209
    Faded_green : BrickColorId # 210
    Turquoise : BrickColorId # 211
    Light_Royal_blue : BrickColorId # 212
    Medium_Royal_blue : BrickColorId # 213
    Rust : BrickColorId # 216
    Brown : BrickColorId # 217
    Reddish_lilac : BrickColorId # 218
    Lilac : BrickColorId # 219
    Light_lilac : BrickColorId # 220
    Bright_purple : BrickColorId # 221
    Light_purple : BrickColorId # 222
    Light_pink : BrickColorId # 223
    Light_brick_yellow : BrickColorId # 224
    Warm_yellowish_orange : BrickColorId # 225
    Cool_yellow : BrickColorId # 226
    Dove_blue : BrickColorId # 232
    Medium_lilac : BrickColorId # 268
    Slime_green : BrickColorId # 301
    Smoky_grey : BrickColorId # 302
    Dark_blue : BrickColorId # 303
    Parsley_green : BrickColorId # 304
    Steel_blue : BrickColorId # 305
    Storm_blue : BrickColorId # 306
    Lapis : BrickColorId # 307
    Dark_indigo : BrickColorId # 308
    Sea_green : BrickColorId # 309
    Shamrock : BrickColorId # 310
    Fossil : BrickColorId # 311
    Mulberry : BrickColorId # 312
    Forest_green : BrickColorId # 313
    Cadet_blue : BrickColorId # 314
    Electric_blue : BrickColorId # 315
    Eggplant : BrickColorId # 316
    Moss : BrickColorId # 317
    Artichoke : BrickColorId # 318
    Sage_green : BrickColorId # 319
    Ghost_grey : BrickColorId # 320
    Lilac_2 : BrickColorId # 321
    Plum : BrickColorId # 322
    Olivine : BrickColorId # 323
    Laurel_green : BrickColorId # 324
    Quill_grey : BrickColorId # 325
    Crimson : BrickColorId # 327
    Mint : BrickColorId # 328
    Baby_blue : BrickColorId # 329
    Carnation_pink : BrickColorId # 330
    Persimmon : BrickColorId # 331
    Maroon : BrickColorId # 332
    Gold_2 : BrickColorId # 333
    Daisy_orange : BrickColorId # 334
    Pearl : BrickColorId # 335
    Fog : BrickColorId # 336
    Salmon : BrickColorId # 337
    Terra_Cotta : BrickColorId # 338
    Cocoa : BrickColorId # 339
    Wheat : BrickColorId # 340
    Buttermilk : BrickColorId # 341
    Mauve : BrickColorId # 342
    Sunrise : BrickColorId # 343
    Tawny : BrickColorId # 344
    Rust_2 : BrickColorId # 345
    Cashmere : BrickColorId # 346
    Khaki : BrickColorId # 347
    Lily_white : BrickColorId # 348
    Seashell : BrickColorId # 349
    Burgundy : BrickColorId # 350
    Cork : BrickColorId # 351
    Burlap : BrickColorId # 352
    Beige : BrickColorId # 353
    Oyster : BrickColorId # 354
    Pine_Cone : BrickColorId # 355
    Fawn_brown : BrickColorId # 356
    Hurricane_grey : BrickColorId # 357
    Cloudy_grey : BrickColorId # 358
    Linen : BrickColorId # 359
    Copper : BrickColorId # 360
    Medium_brown : BrickColorId # 361
    Bronze : BrickColorId # 362
    Flint : BrickColorId # 363
    Dark_taupe : BrickColorId # 364
    Burnt_Sienna : BrickColorId # 365
    Institutional_white : BrickColorId # 1001
    Mid_gray : BrickColorId # 1002
    Really_black : BrickColorId # 1003
    Really_red : BrickColorId # 1004
    Deep_orange : BrickColorId # 1005
    Alder : BrickColorId # 1006
    Dusty_Rose : BrickColorId # 1007
    Olive : BrickColorId # 1008
    New_Yeller : BrickColorId # 1009
    Really_blue : BrickColorId # 1010
    Navy_blue : BrickColorId # 1011
    Deep_blue : BrickColorId # 1012
    Cyan : BrickColorId # 1013
    CGA_brown : BrickColorId # 1014
    Magenta : BrickColorId # 1015
    Pink : BrickColorId # 1016
    Deep_orange_2 : BrickColorId # 1017
    Teal : BrickColorId # 1018
    Toothpaste : BrickColorId # 1019
    Lime_green : BrickColorId # 1020
    Camo : BrickColorId # 1021
    Grime : BrickColorId # 1022
    Lavender : BrickColorId # 1023
    Pastel_light_blue : BrickColorId # 1024
    Pastel_orange : BrickColorId # 1025
    Pastel_violet : BrickColorId # 1026
    Pastel_bluegreen : BrickColorId # 1027
    Pastel_green : BrickColorId # 1028
    Pastel_yellow : BrickColorId # 1029
    Pastel_brown : BrickColorId # 1030
    Royal_purple : BrickColorId # 1031
    Hot_pink : BrickColorId # 1032


class CFrame:
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, comp: Array_1[float]) -> None: ...
    @typing.overload
    def __init__(self, eye: Vector3, look: Vector3) -> None: ...
    @typing.overload
    def __init__(self, n14: float, n24: float, n34: float, n11: float, n12: float, n13: float, n21: float, n22: float, n23: float, n31: float, n32: float, n33: float) -> None: ...
    @typing.overload
    def __init__(self, nx: float = ..., ny: float = ..., nz: float = ...) -> None: ...
    @typing.overload
    def __init__(self, nx: float, ny: float, nz: float, i: float, j: float, k: float, w: float) -> None: ...
    @typing.overload
    def __init__(self, pos: Vector3) -> None: ...
    @typing.overload
    def __init__(self, pos: Vector3, vX: Vector3, vY: Vector3, vZ: Vector3 = ...) -> None: ...
    identity : CFrame
    @property
    def LookVector(self) -> Vector3: ...
    @property
    def Position(self) -> Vector3: ...
    @property
    def RightVector(self) -> Vector3: ...
    @property
    def Rotation(self) -> CFrame: ...
    @property
    def UpVector(self) -> Vector3: ...
    @property
    def X(self) -> float: ...
    @property
    def XVector(self) -> Vector3: ...
    @property
    def Y(self) -> float: ...
    @property
    def YVector(self) -> Vector3: ...
    @property
    def Z(self) -> float: ...
    @property
    def ZVector(self) -> Vector3: ...
    def Equals(self, obj: typing.Any) -> bool: ...
    @staticmethod
    def FromAxisAngle(axis: Vector3, theta: float) -> CFrame: ...
    @staticmethod
    def FromEulerAngles(order: RotationOrder, angles: EulerAngles) -> CFrame: ...
    def GetComponents(self) -> Array_1[float]: ...
    def GetHashCode(self) -> int: ...
    def GetOrientId(self) -> int: ...
    def Inverse(self) -> CFrame: ...
    def IsAxisAligned(self) -> bool: ...
    def Lerp(self, other: CFrame, t: float) -> CFrame: ...
    def __add__(self, a: CFrame, b: Vector3) -> CFrame: ...
    @typing.overload
    def __mul__(self, a: CFrame, b: Vector3) -> Vector3: ...
    @typing.overload
    def __mul__(self, a: CFrame, b: CFrame) -> CFrame: ...
    def __sub__(self, a: CFrame, b: Vector3) -> CFrame: ...
    def PointToObjectSpace(self, v: Vector3) -> Vector3: ...
    def PointToWorldSpace(self, v: Vector3) -> Vector3: ...
    def ToEulerAngles(self) -> EulerAngles: ...
    def ToEulerAnglesXYZ(self) -> Array_1[float]: ...
    def ToObjectSpace(self, other: CFrame) -> CFrame: ...
    def ToString(self) -> str: ...
    def ToWorldSpace(self, cf2: CFrame) -> CFrame: ...
    def VectorToObjectSpace(self, v: Vector3) -> Vector3: ...
    def VectorToWorldSpace(self, v: Vector3) -> Vector3: ...
    # Skipped Angles due to it being static, abstract and generic.

    Angles : Angles_MethodGroup
    class Angles_MethodGroup:
        @typing.overload
        def __call__(self, angles: Array_1[float]) -> CFrame:...
        @typing.overload
        def __call__(self, x: float, y: float, z: float) -> CFrame:...

    # Skipped FromEulerAnglesXYZ due to it being static, abstract and generic.

    FromEulerAnglesXYZ : FromEulerAnglesXYZ_MethodGroup
    class FromEulerAnglesXYZ_MethodGroup:
        @typing.overload
        def __call__(self, angles: Array_1[float]) -> CFrame:...
        @typing.overload
        def __call__(self, x: float, y: float, z: float) -> CFrame:...



class Color3:
    def __init__(self, r: float = ..., g: float = ..., b: float = ...) -> None: ...
    B : float
    G : float
    R : float
    def Equals(self, obj: typing.Any) -> bool: ...
    @staticmethod
    def FromHSV(h: float = ..., s: float = ..., v: float = ...) -> Color3: ...
    @staticmethod
    def FromRGB(r: int = ..., g: int = ..., b: int = ...) -> Color3: ...
    def GetHashCode(self) -> int: ...
    def Lerp(self, other: Color3, alpha: float) -> Color3: ...
    @staticmethod
    def ToHSV(color: Color3) -> Array_1[float]: ...
    def ToString(self) -> str: ...


class Color3uint8:
    def __init__(self, r: int = ..., g: int = ..., b: int = ...) -> None: ...
    B : int
    G : int
    R : int
    def Equals(self, obj: typing.Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    # Operator not supported op_Implicit(color: Color3uint8)
    # Operator not supported op_Implicit(color: Color3)
    def ToString(self) -> str: ...


class ColorSequence:
    @typing.overload
    def __init__(self, c: Color3) -> None: ...
    @typing.overload
    def __init__(self, c0: Color3, c1: Color3) -> None: ...
    @typing.overload
    def __init__(self, keypoints: Array_1[ColorSequenceKeypoint]) -> None: ...
    @typing.overload
    def __init__(self, r: float, g: float, b: float) -> None: ...
    Keypoints : Array_1[ColorSequenceKeypoint]
    def Equals(self, obj: typing.Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def ToString(self) -> str: ...


class ColorSequenceKeypoint:
    def __init__(self, time: float, value: Color3, envelope: int = ...) -> None: ...
    Envelope : int
    Time : float
    Value : Color3uint8
    def Equals(self, obj: typing.Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def ToString(self) -> str: ...


class Content:
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, obj: RbxObject) -> None: ...
    @typing.overload
    def __init__(self, uri: str) -> None: ...
    None : Content
    SourceType : ContentSourceType
    Uri : str
    @property
    def Object(self) -> RbxObject: ...
    @Object.setter
    def Object(self, value: RbxObject) -> RbxObject: ...
    def Equals(self, obj: typing.Any) -> bool: ...
    def GetHashCode(self) -> int: ...


class ContentId:
    def __init__(self, url: str) -> None: ...
    Url : str
    def GetHashCode(self) -> int: ...
    # Operator not supported op_Implicit(url: String)
    # Operator not supported op_Implicit(content: Content)
    # Operator not supported op_Implicit(id: ContentId)
    # Operator not supported op_Implicit(id: ContentId)
    def ToString(self) -> str: ...


class EulerAngles:
    Pitch : float
    Roll : float
    Yaw : float


class Faces(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Right : Faces # 1
    Top : Faces # 2
    Back : Faces # 4
    Left : Faces # 8
    Bottom : Faces # 16
    Front : Faces # 32


class FontFace:
    def __init__(self, family: ContentId, weight: FontWeight = ..., style: FontStyle = ..., cachedFaceId: str = ...) -> None: ...
    Family : ContentId
    Style : FontStyle
    Weight : FontWeight
    @property
    def CachedFaceId(self) -> ContentId: ...
    @CachedFaceId.setter
    def CachedFaceId(self, value: ContentId) -> ContentId: ...
    def Equals(self, obj: typing.Any) -> bool: ...
    @staticmethod
    def FromEnum(font: Font) -> FontFace: ...
    @staticmethod
    def FromId(id: int, weight: FontWeight = ..., style: FontStyle = ...) -> FontFace: ...
    @staticmethod
    def FromName(name: str, weight: FontWeight = ..., style: FontStyle = ...) -> FontFace: ...
    def GetHashCode(self) -> int: ...
    def ToString(self) -> str: ...


class NumberRange:
    @typing.overload
    def __init__(self, min: float = ..., max: float = ...) -> None: ...
    @typing.overload
    def __init__(self, num: float) -> None: ...
    Max : float
    Min : float
    def Equals(self, obj: typing.Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def ToString(self) -> str: ...


class NumberSequence:
    @typing.overload
    def __init__(self, keypoints: Array_1[NumberSequenceKeypoint]) -> None: ...
    @typing.overload
    def __init__(self, n: float) -> None: ...
    @typing.overload
    def __init__(self, n0: float, n1: float) -> None: ...
    Keypoints : Array_1[NumberSequenceKeypoint]
    def Equals(self, obj: typing.Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def ToString(self) -> str: ...


class NumberSequenceKeypoint:
    def __init__(self, time: float, value: float, envelope: float = ...) -> None: ...
    Envelope : float
    Time : float
    Value : float
    def Equals(self, obj: typing.Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def ToString(self) -> str: ...


class Optional_GenericClasses(abc.ABCMeta):
    Generic_Optional_GenericClasses_Optional_1_T = typing.TypeVar('Generic_Optional_GenericClasses_Optional_1_T')
    def __getitem__(self, types : typing.Type[Generic_Optional_GenericClasses_Optional_1_T]) -> typing.Type[Optional_1[Generic_Optional_GenericClasses_Optional_1_T]]: ...

Optional : Optional_GenericClasses

Optional_1_T = typing.TypeVar('Optional_1_T')
class Optional_1(typing.Generic[Optional_1_T]):
    def __init__(self, value: Optional_1_T) -> None: ...
    Value : Optional_1_T
    @property
    def HasValue(self) -> bool: ...
    def Equals(self, obj: typing.Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    # Operator not supported op_Implicit(optional: Optional`1)
    # Operator not supported op_Implicit(value: T)
    def ToString(self) -> str: ...


class PhysicalProperties:
    @typing.overload
    def __init__(self, density: float, friction: float, elasticity: float, frictionWeight: float = ..., elasticityWeight: float = ...) -> None: ...
    @typing.overload
    def __init__(self, material: Material) -> None: ...
    Density : float
    Elasticity : float
    ElasticityWeight : float
    Friction : float
    FrictionWeight : float
    def Equals(self, obj: typing.Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def ToString(self) -> str: ...


class ProtectedString:
    @typing.overload
    def __init__(self, compiled: Array_1[int]) -> None: ...
    @typing.overload
    def __init__(self, value: str) -> None: ...
    IsCompiled : bool
    RawBuffer : Array_1[int]
    def Equals(self, obj: typing.Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    # Operator not supported op_Implicit(value: Byte[])
    # Operator not supported op_Implicit(value: String)
    # Operator not supported op_Implicit(protectedString: ProtectedString)
    # Operator not supported op_Implicit(protectedString: ProtectedString)
    def ToString(self) -> str: ...


class Quaternion:
    @typing.overload
    def __init__(self, cf: CFrame) -> None: ...
    @typing.overload
    def __init__(self, qv: Vector3, qw: float) -> None: ...
    @typing.overload
    def __init__(self, x: float, y: float, z: float, w: float) -> None: ...
    W : float
    X : float
    Y : float
    Z : float
    @property
    def Magnitude(self) -> float: ...
    def Dot(self, other: Quaternion) -> float: ...
    def Equals(self, obj: typing.Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def Lerp(self, other: Quaternion, alpha: float) -> Quaternion: ...
    def __add__(self, a: Quaternion, b: Quaternion) -> Quaternion: ...
    def __truediv__(self, a: Quaternion, f: float) -> Quaternion: ...
    @typing.overload
    def __mul__(self, a: Quaternion, f: float) -> Quaternion: ...
    @typing.overload
    def __mul__(self, a: Quaternion, b: Quaternion) -> Quaternion: ...
    def __sub__(self, a: Quaternion, b: Quaternion) -> Quaternion: ...
    def __neg__(self, a: Quaternion) -> Quaternion: ...
    def Slerp(self, other: Quaternion, alpha: float) -> Quaternion: ...
    def ToCFrame(self) -> CFrame: ...
    def ToEulerAngles(self) -> EulerAngles: ...
    def ToString(self) -> str: ...


class Ray:
    def __init__(self, origin: Vector3 = ..., direction: Vector3 = ...) -> None: ...
    Direction : Vector3
    Origin : Vector3
    @property
    def Unit(self) -> Ray: ...
    def ClosestPoint(self, point: Vector3) -> Vector3: ...
    def Distance(self, point: Vector3) -> float: ...
    def Equals(self, obj: typing.Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def ToString(self) -> str: ...


class Rect:
    @typing.overload
    def __init__(self, min: Vector2 = ..., max: Vector2 = ...) -> None: ...
    @typing.overload
    def __init__(self, minX: float, minY: float, maxX: float, maxY: float) -> None: ...
    Max : Vector2
    Min : Vector2
    @property
    def Height(self) -> float: ...
    @property
    def Width(self) -> float: ...
    def Equals(self, obj: typing.Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def ToString(self) -> str: ...


class Region3:
    def __init__(self, min: Vector3, max: Vector3) -> None: ...
    Max : Vector3
    Min : Vector3
    @property
    def CFrame(self) -> CFrame: ...
    @property
    def Size(self) -> Vector3: ...
    def Equals(self, obj: typing.Any) -> bool: ...
    def ExpandToGrid(self, resolution: float) -> Region3: ...
    def GetHashCode(self) -> int: ...
    def ToString(self) -> str: ...


class Region3int16:
    def __init__(self, min: Vector3int16 = ..., max: Vector3int16 = ...) -> None: ...
    Max : Vector3int16
    Min : Vector3int16
    def Equals(self, obj: typing.Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def ToString(self) -> str: ...


class SharedString:
    @property
    def ComputedKey(self) -> str: ...
    @ComputedKey.setter
    def ComputedKey(self, value: str) -> str: ...
    @property
    def Key(self) -> str: ...
    @Key.setter
    def Key(self, value: str) -> str: ...
    # Skipped property None since it is a reserved python word. Use reflection to access.
    @property
    def SharedValue(self) -> Array_1[int]: ...
    def Equals(self, obj: typing.Any) -> bool: ...
    @staticmethod
    def Find(key: str) -> Array_1[int]: ...
    @staticmethod
    def FromBase64(base64: str) -> SharedString: ...
    @staticmethod
    def FromBuffer(buffer: Array_1[int]) -> SharedString: ...
    @staticmethod
    def FromString(value: str) -> SharedString: ...
    def GetHashCode(self) -> int: ...
    def ToString(self) -> str: ...


class UDim:
    def __init__(self, scale: float = ..., offset: int = ...) -> None: ...
    Offset : int
    Scale : float
    def Equals(self, obj: typing.Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def __add__(self, a: UDim, b: UDim) -> UDim: ...
    def __sub__(self, a: UDim, b: UDim) -> UDim: ...
    def ToString(self) -> str: ...


class UDim2:
    @typing.overload
    def __init__(self, scaleX: float = ..., offsetX: int = ..., scaleY: float = ..., offsetY: int = ...) -> None: ...
    @typing.overload
    def __init__(self, x: UDim, y: UDim) -> None: ...
    X : UDim
    Y : UDim
    @property
    def Height(self) -> UDim: ...
    @property
    def Width(self) -> UDim: ...
    def Equals(self, obj: typing.Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def Lerp(self, other: UDim2, alpha: float) -> UDim2: ...
    def ToString(self) -> str: ...


class UniqueId:
    def __init__(self, random: int, time: int, index: int) -> None: ...
    Index : int
    Random : int
    Time : int
    def ToString(self) -> str: ...


class Vector2:
    @typing.overload
    def __init__(self, coords: Array_1[float]) -> None: ...
    @typing.overload
    def __init__(self, x: float = ..., y: float = ...) -> None: ...
    X : float
    Y : float
    @property
    def Magnitude(self) -> float: ...
    @classmethod
    @property
    def one(cls) -> Vector2: ...
    @property
    def Unit(self) -> Vector2: ...
    @classmethod
    @property
    def xAxis(cls) -> Vector2: ...
    @classmethod
    @property
    def yAxis(cls) -> Vector2: ...
    @classmethod
    @property
    def zero(cls) -> Vector2: ...
    def Cross(self, other: Vector2) -> Vector2: ...
    def Dot(self, other: Vector2) -> float: ...
    def Equals(self, obj: typing.Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def Lerp(self, other: Vector2, t: float) -> Vector2: ...
    @typing.overload
    def __add__(self, n: float, v: Vector2) -> Vector2: ...
    @typing.overload
    def __add__(self, v: Vector2, n: float) -> Vector2: ...
    @typing.overload
    def __add__(self, a: Vector2, b: Vector2) -> Vector2: ...
    @typing.overload
    def __truediv__(self, n: float, v: Vector2) -> Vector2: ...
    @typing.overload
    def __truediv__(self, v: Vector2, n: float) -> Vector2: ...
    @typing.overload
    def __truediv__(self, a: Vector2, b: Vector2) -> Vector2: ...
    @typing.overload
    def __mul__(self, n: float, v: Vector2) -> Vector2: ...
    @typing.overload
    def __mul__(self, v: Vector2, n: float) -> Vector2: ...
    @typing.overload
    def __mul__(self, a: Vector2, b: Vector2) -> Vector2: ...
    @typing.overload
    def __sub__(self, n: float, v: Vector2) -> Vector2: ...
    @typing.overload
    def __sub__(self, v: Vector2, n: float) -> Vector2: ...
    @typing.overload
    def __sub__(self, a: Vector2, b: Vector2) -> Vector2: ...
    def __neg__(self, v: Vector2) -> Vector2: ...
    def ToString(self) -> str: ...


class Vector2int16:
    # Constructor .ctor(x : Int32, y : Int32) was skipped since it collides with above method
    def __init__(self, x: int = ..., y: int = ...) -> None: ...
    X : int
    Y : int
    def Equals(self, obj: typing.Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    @typing.overload
    def __add__(self, n: int, v: Vector2int16) -> Vector2int16: ...
    @typing.overload
    def __add__(self, v: Vector2int16, n: int) -> Vector2int16: ...
    @typing.overload
    def __add__(self, a: Vector2int16, b: Vector2int16) -> Vector2int16: ...
    @typing.overload
    def __truediv__(self, n: int, v: Vector2int16) -> Vector2int16: ...
    @typing.overload
    def __truediv__(self, v: Vector2int16, n: int) -> Vector2int16: ...
    @typing.overload
    def __truediv__(self, a: Vector2int16, b: Vector2int16) -> Vector2int16: ...
    @typing.overload
    def __mul__(self, n: int, v: Vector2int16) -> Vector2int16: ...
    @typing.overload
    def __mul__(self, v: Vector2int16, n: int) -> Vector2int16: ...
    @typing.overload
    def __mul__(self, a: Vector2int16, b: Vector2int16) -> Vector2int16: ...
    @typing.overload
    def __sub__(self, n: int, v: Vector2int16) -> Vector2int16: ...
    @typing.overload
    def __sub__(self, v: Vector2int16, n: int) -> Vector2int16: ...
    @typing.overload
    def __sub__(self, a: Vector2int16, b: Vector2int16) -> Vector2int16: ...
    def ToString(self) -> str: ...


class Vector3:
    @typing.overload
    def __init__(self, coords: Array_1[float]) -> None: ...
    @typing.overload
    def __init__(self, x: float = ..., y: float = ..., z: float = ...) -> None: ...
    one : Vector3
    X : float
    xAxis : Vector3
    Y : float
    yAxis : Vector3
    Z : float
    zAxis : Vector3
    zero : Vector3
    @classmethod
    @property
    def Back(cls) -> Vector3: ...
    @property
    def Magnitude(self) -> float: ...
    @classmethod
    @property
    def Right(cls) -> Vector3: ...
    @property
    def Unit(self) -> Vector3: ...
    @classmethod
    @property
    def Up(cls) -> Vector3: ...
    def Cross(self, other: Vector3) -> Vector3: ...
    def Dot(self, other: Vector3) -> float: ...
    def Equals(self, obj: typing.Any) -> bool: ...
    @staticmethod
    def FromAxis(axis: Axis) -> Vector3: ...
    @staticmethod
    def FromNormalId(normalId: NormalId) -> Vector3: ...
    def GetHashCode(self) -> int: ...
    def IsClose(self, other: Vector3, epsilon: float = ...) -> bool: ...
    def Lerp(self, other: Vector3, t: float) -> Vector3: ...
    @typing.overload
    def __add__(self, n: float, v: Vector3) -> Vector3: ...
    @typing.overload
    def __add__(self, v: Vector3, n: float) -> Vector3: ...
    @typing.overload
    def __add__(self, a: Vector3, b: Vector3) -> Vector3: ...
    @typing.overload
    def __truediv__(self, n: float, v: Vector3) -> Vector3: ...
    @typing.overload
    def __truediv__(self, v: Vector3, n: float) -> Vector3: ...
    @typing.overload
    def __truediv__(self, a: Vector3, b: Vector3) -> Vector3: ...
    @typing.overload
    def __mul__(self, n: float, v: Vector3) -> Vector3: ...
    @typing.overload
    def __mul__(self, v: Vector3, n: float) -> Vector3: ...
    @typing.overload
    def __mul__(self, a: Vector3, b: Vector3) -> Vector3: ...
    @typing.overload
    def __sub__(self, n: float, v: Vector3) -> Vector3: ...
    @typing.overload
    def __sub__(self, v: Vector3, n: float) -> Vector3: ...
    @typing.overload
    def __sub__(self, a: Vector3, b: Vector3) -> Vector3: ...
    def __neg__(self, v: Vector3) -> Vector3: ...
    def ToNormalId(self) -> int: ...
    def ToString(self) -> str: ...


class Vector3int16:
    # Constructor .ctor(x : Int32, y : Int32, z : Int32) was skipped since it collides with above method
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, x: int = ..., y: int = ..., z: int = ...) -> None: ...
    X : int
    Y : int
    Z : int
    def Equals(self, obj: typing.Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    @typing.overload
    def __add__(self, n: int, v: Vector3int16) -> Vector3int16: ...
    @typing.overload
    def __add__(self, v: Vector3int16, n: int) -> Vector3int16: ...
    @typing.overload
    def __add__(self, a: Vector3int16, b: Vector3int16) -> Vector3int16: ...
    @typing.overload
    def __truediv__(self, n: int, v: Vector3int16) -> Vector3int16: ...
    @typing.overload
    def __truediv__(self, v: Vector3int16, n: int) -> Vector3int16: ...
    @typing.overload
    def __truediv__(self, a: Vector3int16, b: Vector3int16) -> Vector3int16: ...
    @typing.overload
    def __mul__(self, n: int, v: Vector3int16) -> Vector3int16: ...
    @typing.overload
    def __mul__(self, v: Vector3int16, n: int) -> Vector3int16: ...
    @typing.overload
    def __mul__(self, a: Vector3int16, b: Vector3int16) -> Vector3int16: ...
    @typing.overload
    def __sub__(self, n: int, v: Vector3int16) -> Vector3int16: ...
    @typing.overload
    def __sub__(self, v: Vector3int16, n: int) -> Vector3int16: ...
    @typing.overload
    def __sub__(self, a: Vector3int16, b: Vector3int16) -> Vector3int16: ...
    def ToString(self) -> str: ...

