import typing, abc
from RobloxFiles import Property, IAttributeToken_1, AttributeType, RbxAttribute
from System.Xml import XmlNode, XmlDocument
from RobloxFiles.DataTypes import BrickColor, CFrame, Color3, ColorSequence, FontFace, NumberRange, NumberSequence, Rect, UDim2, UDim, Vector2, Vector3
from System import Enum

class AxesToken(IXmlPropertyToken):
    def __init__(self) -> None: ...
    @property
    def XmlPropertyToken(self) -> str: ...
    def ReadProperty(self, prop: Property, token: XmlNode) -> bool: ...
    def WriteProperty(self, prop: Property, doc: XmlDocument, node: XmlNode) -> None: ...


class BinaryStringToken(IXmlPropertyToken):
    def __init__(self) -> None: ...
    @property
    def XmlPropertyToken(self) -> str: ...
    def ReadProperty(self, prop: Property, token: XmlNode) -> bool: ...
    def WriteProperty(self, prop: Property, doc: XmlDocument, node: XmlNode) -> None: ...


class BoolToken(IAttributeToken_1[bool], IXmlPropertyToken):
    def __init__(self) -> None: ...
    @property
    def AttributeType(self) -> AttributeType: ...
    @property
    def XmlPropertyToken(self) -> str: ...
    def ReadAttribute(self, attr: RbxAttribute) -> bool: ...
    def ReadProperty(self, prop: Property, token: XmlNode) -> bool: ...
    def WriteAttribute(self, attr: RbxAttribute, value: bool) -> None: ...
    def WriteProperty(self, prop: Property, doc: XmlDocument, node: XmlNode) -> None: ...


class BrickColorToken(IAttributeToken_1[BrickColor], IXmlPropertyToken):
    def __init__(self) -> None: ...
    @property
    def AttributeType(self) -> AttributeType: ...
    @property
    def XmlPropertyToken(self) -> str: ...
    def ReadAttribute(self, attr: RbxAttribute) -> BrickColor: ...
    def ReadProperty(self, prop: Property, token: XmlNode) -> bool: ...
    def WriteAttribute(self, attr: RbxAttribute, value: BrickColor) -> None: ...
    def WriteProperty(self, prop: Property, doc: XmlDocument, node: XmlNode) -> None: ...


class CFrameToken(IAttributeToken_1[CFrame], IXmlPropertyToken):
    def __init__(self) -> None: ...
    @property
    def AttributeType(self) -> AttributeType: ...
    @property
    def XmlPropertyToken(self) -> str: ...
    def ReadAttribute(self, attribute: RbxAttribute) -> CFrame: ...
    @staticmethod
    def ReadCFrame(token: XmlNode) -> CFrame: ...
    def ReadProperty(self, prop: Property, token: XmlNode) -> bool: ...
    def WriteAttribute(self, attribute: RbxAttribute, value: CFrame) -> None: ...
    @staticmethod
    def WriteCFrame(cf: CFrame, doc: XmlDocument, node: XmlNode) -> None: ...
    def WriteProperty(self, prop: Property, doc: XmlDocument, node: XmlNode) -> None: ...


class Color3Token(IAttributeToken_1[Color3], IXmlPropertyToken):
    def __init__(self) -> None: ...
    @property
    def AttributeType(self) -> AttributeType: ...
    @property
    def XmlPropertyToken(self) -> str: ...
    def ReadAttribute(self, attr: RbxAttribute) -> Color3: ...
    @staticmethod
    def ReadColor3(attr: RbxAttribute) -> Color3: ...
    def ReadProperty(self, prop: Property, token: XmlNode) -> bool: ...
    def WriteAttribute(self, attr: RbxAttribute, value: Color3) -> None: ...
    @staticmethod
    def WriteColor3(attr: RbxAttribute, value: Color3) -> None: ...
    def WriteProperty(self, prop: Property, doc: XmlDocument, node: XmlNode) -> None: ...


class Color3uint8Token(IXmlPropertyToken):
    def __init__(self) -> None: ...
    @property
    def XmlPropertyToken(self) -> str: ...
    def ReadProperty(self, prop: Property, token: XmlNode) -> bool: ...
    def WriteProperty(self, prop: Property, doc: XmlDocument, node: XmlNode) -> None: ...


class ColorSequenceToken(IAttributeToken_1[ColorSequence], IXmlPropertyToken):
    def __init__(self) -> None: ...
    @property
    def AttributeType(self) -> AttributeType: ...
    @property
    def XmlPropertyToken(self) -> str: ...
    def ReadAttribute(self, attr: RbxAttribute) -> ColorSequence: ...
    def ReadProperty(self, prop: Property, token: XmlNode) -> bool: ...
    def WriteAttribute(self, attr: RbxAttribute, value: ColorSequence) -> None: ...
    def WriteProperty(self, prop: Property, doc: XmlDocument, node: XmlNode) -> None: ...


class ContentIdToken(IXmlPropertyToken):
    def __init__(self) -> None: ...
    @property
    def XmlPropertyToken(self) -> str: ...
    def ReadProperty(self, prop: Property, token: XmlNode) -> bool: ...
    def WriteProperty(self, prop: Property, doc: XmlDocument, node: XmlNode) -> None: ...


class ContentToken(IXmlPropertyToken):
    def __init__(self) -> None: ...
    @property
    def XmlPropertyToken(self) -> str: ...
    def ReadProperty(self, prop: Property, token: XmlNode) -> bool: ...
    def WriteProperty(self, prop: Property, doc: XmlDocument, node: XmlNode) -> None: ...


class DoubleToken(IAttributeToken_1[float], IXmlPropertyToken):
    def __init__(self) -> None: ...
    @property
    def AttributeType(self) -> AttributeType: ...
    @property
    def XmlPropertyToken(self) -> str: ...
    def ReadAttribute(self, attr: RbxAttribute) -> float: ...
    def ReadProperty(self, prop: Property, token: XmlNode) -> bool: ...
    def WriteAttribute(self, attr: RbxAttribute, value: float) -> None: ...
    def WriteProperty(self, prop: Property, doc: XmlDocument, node: XmlNode) -> None: ...


class EnumToken(IAttributeToken_1[Enum], IXmlPropertyToken):
    def __init__(self) -> None: ...
    @property
    def AttributeType(self) -> AttributeType: ...
    @property
    def XmlPropertyToken(self) -> str: ...
    def ReadProperty(self, prop: Property, token: XmlNode) -> bool: ...
    def WriteProperty(self, prop: Property, doc: XmlDocument, node: XmlNode) -> None: ...


class FacesToken(IXmlPropertyToken):
    def __init__(self) -> None: ...
    @property
    def XmlPropertyToken(self) -> str: ...
    def ReadProperty(self, prop: Property, token: XmlNode) -> bool: ...
    def WriteProperty(self, prop: Property, doc: XmlDocument, node: XmlNode) -> None: ...


class FloatToken(IAttributeToken_1[float], IXmlPropertyToken):
    def __init__(self) -> None: ...
    @property
    def AttributeType(self) -> AttributeType: ...
    @property
    def XmlPropertyToken(self) -> str: ...
    def ReadAttribute(self, attr: RbxAttribute) -> float: ...
    def ReadProperty(self, prop: Property, token: XmlNode) -> bool: ...
    def WriteAttribute(self, attr: RbxAttribute, value: float) -> None: ...
    def WriteProperty(self, prop: Property, doc: XmlDocument, node: XmlNode) -> None: ...


class FontToken(IAttributeToken_1[FontFace], IXmlPropertyToken):
    def __init__(self) -> None: ...
    @property
    def AttributeType(self) -> AttributeType: ...
    @property
    def XmlPropertyToken(self) -> str: ...
    def ReadAttribute(self, attribute: RbxAttribute) -> FontFace: ...
    def ReadProperty(self, prop: Property, node: XmlNode) -> bool: ...
    def WriteAttribute(self, attribute: RbxAttribute, value: FontFace) -> None: ...
    def WriteProperty(self, prop: Property, doc: XmlDocument, node: XmlNode) -> None: ...


class Int64Token(IXmlPropertyToken):
    def __init__(self) -> None: ...
    @property
    def XmlPropertyToken(self) -> str: ...
    def ReadProperty(self, prop: Property, token: XmlNode) -> bool: ...
    def WriteProperty(self, prop: Property, doc: XmlDocument, node: XmlNode) -> None: ...


class IntToken(IAttributeToken_1[int], IXmlPropertyToken):
    def __init__(self) -> None: ...
    @property
    def AttributeType(self) -> AttributeType: ...
    @property
    def XmlPropertyToken(self) -> str: ...
    def ReadAttribute(self, attr: RbxAttribute) -> int: ...
    def ReadProperty(self, prop: Property, token: XmlNode) -> bool: ...
    def WriteAttribute(self, attr: RbxAttribute, value: int) -> None: ...
    def WriteProperty(self, prop: Property, doc: XmlDocument, node: XmlNode) -> None: ...


class IXmlPropertyToken(typing.Protocol):
    @property
    def XmlPropertyToken(self) -> str: ...
    @abc.abstractmethod
    def ReadProperty(self, prop: Property, node: XmlNode) -> bool: ...
    @abc.abstractmethod
    def WriteProperty(self, prop: Property, doc: XmlDocument, node: XmlNode) -> None: ...


class NumberRangeToken(IAttributeToken_1[NumberRange], IXmlPropertyToken):
    def __init__(self) -> None: ...
    @property
    def AttributeType(self) -> AttributeType: ...
    @property
    def XmlPropertyToken(self) -> str: ...
    def ReadAttribute(self, attr: RbxAttribute) -> NumberRange: ...
    def ReadProperty(self, prop: Property, token: XmlNode) -> bool: ...
    def WriteAttribute(self, attr: RbxAttribute, value: NumberRange) -> None: ...
    def WriteProperty(self, prop: Property, doc: XmlDocument, node: XmlNode) -> None: ...


class NumberSequenceToken(IAttributeToken_1[NumberSequence], IXmlPropertyToken):
    def __init__(self) -> None: ...
    @property
    def AttributeType(self) -> AttributeType: ...
    @property
    def XmlPropertyToken(self) -> str: ...
    def ReadAttribute(self, attr: RbxAttribute) -> NumberSequence: ...
    def ReadProperty(self, prop: Property, token: XmlNode) -> bool: ...
    def WriteAttribute(self, attr: RbxAttribute, value: NumberSequence) -> None: ...
    def WriteProperty(self, prop: Property, doc: XmlDocument, node: XmlNode) -> None: ...


class OptionalCFrameToken(IXmlPropertyToken):
    def __init__(self) -> None: ...
    @property
    def XmlPropertyToken(self) -> str: ...
    def ReadProperty(self, prop: Property, token: XmlNode) -> bool: ...
    def WriteProperty(self, prop: Property, doc: XmlDocument, node: XmlNode) -> None: ...


class PhysicalPropertiesToken(IXmlPropertyToken):
    def __init__(self) -> None: ...
    @property
    def XmlPropertyToken(self) -> str: ...
    def ReadProperty(self, prop: Property, token: XmlNode) -> bool: ...
    def WriteProperty(self, prop: Property, doc: XmlDocument, node: XmlNode) -> None: ...


class ProtectedStringToken(IXmlPropertyToken):
    def __init__(self) -> None: ...
    @property
    def XmlPropertyToken(self) -> str: ...
    def ReadProperty(self, prop: Property, token: XmlNode) -> bool: ...
    def WriteProperty(self, prop: Property, doc: XmlDocument, node: XmlNode) -> None: ...


class RayToken(IXmlPropertyToken):
    def __init__(self) -> None: ...
    @property
    def XmlPropertyToken(self) -> str: ...
    def ReadProperty(self, prop: Property, token: XmlNode) -> bool: ...
    def WriteProperty(self, prop: Property, doc: XmlDocument, node: XmlNode) -> None: ...


class RectToken(IAttributeToken_1[Rect], IXmlPropertyToken):
    def __init__(self) -> None: ...
    @property
    def AttributeType(self) -> AttributeType: ...
    @property
    def XmlPropertyToken(self) -> str: ...
    def ReadAttribute(self, attr: RbxAttribute) -> Rect: ...
    def ReadProperty(self, prop: Property, token: XmlNode) -> bool: ...
    def WriteAttribute(self, attr: RbxAttribute, value: Rect) -> None: ...
    def WriteProperty(self, prop: Property, doc: XmlDocument, node: XmlNode) -> None: ...


class RefToken(IXmlPropertyToken):
    def __init__(self) -> None: ...
    @property
    def XmlPropertyToken(self) -> str: ...
    def ReadProperty(self, prop: Property, token: XmlNode) -> bool: ...
    def WriteProperty(self, prop: Property, doc: XmlDocument, node: XmlNode) -> None: ...


class SecurityCapabilitiesToken(IXmlPropertyToken):
    def __init__(self) -> None: ...
    @property
    def XmlPropertyToken(self) -> str: ...
    def ReadProperty(self, prop: Property, node: XmlNode) -> bool: ...
    def WriteProperty(self, prop: Property, doc: XmlDocument, node: XmlNode) -> None: ...


class SharedStringToken(IXmlPropertyToken):
    def __init__(self) -> None: ...
    @property
    def XmlPropertyToken(self) -> str: ...
    def ReadProperty(self, prop: Property, token: XmlNode) -> bool: ...
    def WriteProperty(self, prop: Property, doc: XmlDocument, node: XmlNode) -> None: ...


class StringToken(IAttributeToken_1[str], IXmlPropertyToken):
    def __init__(self) -> None: ...
    @property
    def AttributeType(self) -> AttributeType: ...
    @property
    def XmlPropertyToken(self) -> str: ...
    def ReadAttribute(self, attr: RbxAttribute) -> str: ...
    def ReadProperty(self, prop: Property, token: XmlNode) -> bool: ...
    def WriteAttribute(self, attr: RbxAttribute, value: str) -> None: ...
    def WriteProperty(self, prop: Property, doc: XmlDocument, node: XmlNode) -> None: ...


class UDim2Token(IAttributeToken_1[UDim2], IXmlPropertyToken):
    def __init__(self) -> None: ...
    @property
    def AttributeType(self) -> AttributeType: ...
    @property
    def XmlPropertyToken(self) -> str: ...
    def ReadAttribute(self, attr: RbxAttribute) -> UDim2: ...
    def ReadProperty(self, property: Property, token: XmlNode) -> bool: ...
    def WriteAttribute(self, attr: RbxAttribute, value: UDim2) -> None: ...
    def WriteProperty(self, prop: Property, doc: XmlDocument, node: XmlNode) -> None: ...


class UDimToken(IAttributeToken_1[UDim], IXmlPropertyToken):
    def __init__(self) -> None: ...
    @property
    def AttributeType(self) -> AttributeType: ...
    @property
    def XmlPropertyToken(self) -> str: ...
    def ReadAttribute(self, attr: RbxAttribute) -> UDim: ...
    def ReadProperty(self, property: Property, token: XmlNode) -> bool: ...
    def WriteAttribute(self, attr: RbxAttribute, value: UDim) -> None: ...
    def WriteProperty(self, prop: Property, doc: XmlDocument, node: XmlNode) -> None: ...
    # Skipped ReadUDim due to it being static, abstract and generic.

    ReadUDim : ReadUDim_MethodGroup
    class ReadUDim_MethodGroup:
        @typing.overload
        def __call__(self, attr: RbxAttribute) -> UDim:...
        @typing.overload
        def __call__(self, token: XmlNode, prefix: str = ...) -> UDim:...

    # Skipped WriteUDim due to it being static, abstract and generic.

    WriteUDim : WriteUDim_MethodGroup
    class WriteUDim_MethodGroup:
        @typing.overload
        def __call__(self, attr: RbxAttribute, value: UDim) -> None:...
        @typing.overload
        def __call__(self, doc: XmlDocument, node: XmlNode, value: UDim, prefix: str = ...) -> None:...



class UniqueIdToken(IXmlPropertyToken):
    def __init__(self) -> None: ...
    @property
    def XmlPropertyToken(self) -> str: ...
    def ReadProperty(self, prop: Property, token: XmlNode) -> bool: ...
    def WriteProperty(self, prop: Property, doc: XmlDocument, node: XmlNode) -> None: ...


class Vector2Token(IAttributeToken_1[Vector2], IXmlPropertyToken):
    def __init__(self) -> None: ...
    @property
    def AttributeType(self) -> AttributeType: ...
    @property
    def XmlPropertyToken(self) -> str: ...
    def ReadAttribute(self, attr: RbxAttribute) -> Vector2: ...
    def ReadProperty(self, property: Property, token: XmlNode) -> bool: ...
    def WriteAttribute(self, attr: RbxAttribute, value: Vector2) -> None: ...
    def WriteProperty(self, prop: Property, doc: XmlDocument, node: XmlNode) -> None: ...
    # Skipped ReadVector2 due to it being static, abstract and generic.

    ReadVector2 : ReadVector2_MethodGroup
    class ReadVector2_MethodGroup:
        @typing.overload
        def __call__(self, attr: RbxAttribute) -> Vector2:...
        @typing.overload
        def __call__(self, token: XmlNode) -> Vector2:...

    # Skipped WriteVector2 due to it being static, abstract and generic.

    WriteVector2 : WriteVector2_MethodGroup
    class WriteVector2_MethodGroup:
        @typing.overload
        def __call__(self, attr: RbxAttribute, value: Vector2) -> None:...
        @typing.overload
        def __call__(self, doc: XmlDocument, node: XmlNode, value: Vector2) -> None:...



class Vector3int16Token(IXmlPropertyToken):
    def __init__(self) -> None: ...
    @property
    def XmlPropertyToken(self) -> str: ...
    def ReadProperty(self, property: Property, token: XmlNode) -> bool: ...
    def WriteProperty(self, prop: Property, doc: XmlDocument, node: XmlNode) -> None: ...


class Vector3Token(IAttributeToken_1[Vector3], IXmlPropertyToken):
    def __init__(self) -> None: ...
    @property
    def AttributeType(self) -> AttributeType: ...
    @property
    def XmlPropertyToken(self) -> str: ...
    def ReadAttribute(self, attr: RbxAttribute) -> Vector3: ...
    def ReadProperty(self, property: Property, token: XmlNode) -> bool: ...
    def WriteAttribute(self, attr: RbxAttribute, value: Vector3) -> None: ...
    def WriteProperty(self, prop: Property, doc: XmlDocument, node: XmlNode) -> None: ...
    # Skipped ReadVector3 due to it being static, abstract and generic.

    ReadVector3 : ReadVector3_MethodGroup
    class ReadVector3_MethodGroup:
        @typing.overload
        def __call__(self, attr: RbxAttribute) -> Vector3:...
        @typing.overload
        def __call__(self, token: XmlNode) -> Vector3:...

    # Skipped WriteVector3 due to it being static, abstract and generic.

    WriteVector3 : WriteVector3_MethodGroup
    class WriteVector3_MethodGroup:
        @typing.overload
        def __call__(self, attr: RbxAttribute, value: Vector3) -> None:...
        @typing.overload
        def __call__(self, doc: XmlDocument, node: XmlNode, value: Vector3) -> None:...


