import typing, abc
from System import Array_1, Func_3, Func_2
from System.IO import BinaryReader, Stream, BinaryWriter
from RobloxFiles import BinaryRobloxFile
from System.Collections.Generic import List_1
from System.Text import StringBuilder

class BinaryRobloxFileChunk:
    @typing.overload
    def __init__(self, reader: BinaryRobloxFileReader) -> None: ...
    @typing.overload
    def __init__(self, writer: BinaryRobloxFileWriter, compress: bool = ...) -> None: ...
    ChunkType : str
    CompressedData : Array_1[int]
    CompressedSize : int
    Data : Array_1[int]
    Reserved : int
    Size : int
    @property
    def Handler(self) -> IBinaryFileChunk: ...
    @Handler.setter
    def Handler(self, value: IBinaryFileChunk) -> IBinaryFileChunk: ...
    @property
    def HasCompressedData(self) -> bool: ...
    @property
    def HasWriteBuffer(self) -> bool: ...
    @HasWriteBuffer.setter
    def HasWriteBuffer(self, value: bool) -> bool: ...
    @property
    def WriteBuffer(self) -> Array_1[int]: ...
    @WriteBuffer.setter
    def WriteBuffer(self, value: Array_1[int]) -> Array_1[int]: ...
    def ToString(self) -> str: ...
    def WriteChunk(self, writer: BinaryRobloxFileWriter) -> None: ...


class BinaryRobloxFileReader(BinaryReader):
    def __init__(self, file: BinaryRobloxFile, stream: Stream) -> None: ...
    File : BinaryRobloxFile
    @property
    def BaseStream(self) -> Stream: ...
    def GetLastStringBuffer(self) -> Array_1[int]: ...
    def ReadFloat(self) -> float: ...
    def ReadObjectIds(self, count: int) -> List_1[int]: ...
    def ReadString(self) -> str: ...
    def RotateFloat(self, buffer: Array_1[int], startIndex: int) -> float: ...
    def RotateInt32(self, buffer: Array_1[int], startIndex: int) -> int: ...
    def RotateInt64(self, buffer: Array_1[int], startIndex: int) -> int: ...
    # Skipped ReadInterleaved due to it being static, abstract and generic.

    ReadInterleaved : ReadInterleaved_MethodGroup
    class ReadInterleaved_MethodGroup:
        def __getitem__(self, t:typing.Type[ReadInterleaved_1_T1]) -> ReadInterleaved_1[ReadInterleaved_1_T1]: ...

        ReadInterleaved_1_T1 = typing.TypeVar('ReadInterleaved_1_T1')
        class ReadInterleaved_1(typing.Generic[ReadInterleaved_1_T1]):
            ReadInterleaved_1_T = BinaryRobloxFileReader.ReadInterleaved_MethodGroup.ReadInterleaved_1_T1
            def __call__(self, count: int, transform: Func_3[Array_1[int], int, ReadInterleaved_1_T]) -> Array_1[ReadInterleaved_1_T]:...




class BinaryRobloxFileWriter(BinaryWriter):
    def __init__(self, file: BinaryRobloxFile, workBuffer: Stream) -> None: ...
    File : BinaryRobloxFile
    @property
    def BaseStream(self) -> Stream: ...
    @property
    def Chunk(self) -> IBinaryFileChunk: ...
    @Chunk.setter
    def Chunk(self, value: IBinaryFileChunk) -> IBinaryFileChunk: ...
    @property
    def ChunkStart(self) -> int: ...
    @ChunkStart.setter
    def ChunkStart(self, value: int) -> int: ...
    @property
    def ChunkType(self) -> str: ...
    @ChunkType.setter
    def ChunkType(self, value: str) -> str: ...
    @property
    def WritingChunk(self) -> bool: ...
    @WritingChunk.setter
    def WritingChunk(self, value: bool) -> bool: ...
    def RotateFloat(self, value: float) -> float: ...
    def RotateInt(self, value: int) -> int: ...
    def RotateLong(self, value: int) -> int: ...
    def WriteFloats(self, values: List_1[float]) -> None: ...
    def WriteInts(self, values: List_1[int]) -> None: ...
    def WriteLongs(self, values: List_1[int]) -> None: ...
    def WriteObjectIds(self, values: List_1[int]) -> None: ...
    def WriteString(self, value: str, raw: bool = ...) -> None: ...
    # Skipped GetBytes due to it being static, abstract and generic.

    GetBytes : GetBytes_MethodGroup
    class GetBytes_MethodGroup:
        def __getitem__(self, t:typing.Type[GetBytes_1_T1]) -> GetBytes_1[GetBytes_1_T1]: ...

        GetBytes_1_T1 = typing.TypeVar('GetBytes_1_T1')
        class GetBytes_1(typing.Generic[GetBytes_1_T1]):
            GetBytes_1_T = BinaryRobloxFileWriter.GetBytes_MethodGroup.GetBytes_1_T1
            def __call__(self, value: GetBytes_1_T) -> Array_1[int]:...


    # Skipped SizeOf due to it being static, abstract and generic.

    SizeOf : SizeOf_MethodGroup
    class SizeOf_MethodGroup:
        def __getitem__(self, t:typing.Type[SizeOf_1_T1]) -> SizeOf_1[SizeOf_1_T1]: ...

        SizeOf_1_T1 = typing.TypeVar('SizeOf_1_T1')
        class SizeOf_1(typing.Generic[SizeOf_1_T1]):
            SizeOf_1_T = BinaryRobloxFileWriter.SizeOf_MethodGroup.SizeOf_1_T1
            def __call__(self) -> int:...


    # Skipped WriteInterleaved due to it being static, abstract and generic.

    WriteInterleaved : WriteInterleaved_MethodGroup
    class WriteInterleaved_MethodGroup:
        def __getitem__(self, t:typing.Type[WriteInterleaved_1_T1]) -> WriteInterleaved_1[WriteInterleaved_1_T1]: ...

        WriteInterleaved_1_T1 = typing.TypeVar('WriteInterleaved_1_T1')
        class WriteInterleaved_1(typing.Generic[WriteInterleaved_1_T1]):
            WriteInterleaved_1_T = BinaryRobloxFileWriter.WriteInterleaved_MethodGroup.WriteInterleaved_1_T1
            def __call__(self, values: List_1[WriteInterleaved_1_T], encode: Func_2[WriteInterleaved_1_T, WriteInterleaved_1_T] = ...) -> None:...




class IBinaryFileChunk(typing.Protocol):
    @abc.abstractmethod
    def Load(self, reader: BinaryRobloxFileReader) -> None: ...
    @abc.abstractmethod
    def Save(self, writer: BinaryRobloxFileWriter) -> None: ...
    @abc.abstractmethod
    def WriteInfo(self, builder: StringBuilder) -> None: ...

