import typing
from RobloxFiles.BinaryFormat import IBinaryFileChunk, BinaryRobloxFileReader, BinaryRobloxFileWriter
from System.Collections.Generic import List_1, Dictionary_2
from System.Text import StringBuilder
from RobloxFiles import PropertyType
from System import Array_1

class INST(IBinaryFileChunk):
    def __init__(self) -> None: ...
    @property
    def ClassIndex(self) -> int: ...
    @ClassIndex.setter
    def ClassIndex(self, value: int) -> int: ...
    @property
    def ClassName(self) -> str: ...
    @ClassName.setter
    def ClassName(self, value: str) -> str: ...
    @property
    def IsService(self) -> bool: ...
    @IsService.setter
    def IsService(self, value: bool) -> bool: ...
    @property
    def NumObjects(self) -> int: ...
    @NumObjects.setter
    def NumObjects(self, value: int) -> int: ...
    @property
    def ObjectIds(self) -> List_1[int]: ...
    @ObjectIds.setter
    def ObjectIds(self, value: List_1[int]) -> List_1[int]: ...
    @property
    def RootedServices(self) -> List_1[bool]: ...
    @RootedServices.setter
    def RootedServices(self, value: List_1[bool]) -> List_1[bool]: ...
    def Load(self, reader: BinaryRobloxFileReader) -> None: ...
    def Save(self, writer: BinaryRobloxFileWriter) -> None: ...
    def ToString(self) -> str: ...
    def WriteInfo(self, builder: StringBuilder) -> None: ...


class META(IBinaryFileChunk):
    def __init__(self) -> None: ...
    Data : Dictionary_2[str, str]
    def Load(self, reader: BinaryRobloxFileReader) -> None: ...
    def Save(self, writer: BinaryRobloxFileWriter) -> None: ...
    def WriteInfo(self, builder: StringBuilder) -> None: ...


class PRNT(IBinaryFileChunk):
    def __init__(self) -> None: ...
    def Load(self, reader: BinaryRobloxFileReader) -> None: ...
    def Save(self, writer: BinaryRobloxFileWriter) -> None: ...
    def WriteInfo(self, builder: StringBuilder) -> None: ...


class PROP(IBinaryFileChunk):
    def __init__(self) -> None: ...
    @property
    def ClassIndex(self) -> int: ...
    @ClassIndex.setter
    def ClassIndex(self, value: int) -> int: ...
    @property
    def ClassName(self) -> str: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...
    @property
    def Type(self) -> PropertyType: ...
    @Type.setter
    def Type(self, value: PropertyType) -> PropertyType: ...
    def Load(self, reader: BinaryRobloxFileReader) -> None: ...
    def Save(self, writer: BinaryRobloxFileWriter) -> None: ...
    def ToString(self) -> str: ...
    def WriteInfo(self, builder: StringBuilder) -> None: ...


class RbxSignature:
    PublicKeyId : int
    SignatureType : RbxSignatureType
    Value : Array_1[int]


class RbxSignatureType(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Ed25519 : RbxSignatureType # 0


class SIGN(IBinaryFileChunk):
    def __init__(self) -> None: ...
    Signatures : Array_1[RbxSignature]
    def Load(self, reader: BinaryRobloxFileReader) -> None: ...
    def Save(self, writer: BinaryRobloxFileWriter) -> None: ...
    def WriteInfo(self, builder: StringBuilder) -> None: ...


class SSTR(IBinaryFileChunk):
    def __init__(self) -> None: ...
    def Load(self, reader: BinaryRobloxFileReader) -> None: ...
    def Save(self, writer: BinaryRobloxFileWriter) -> None: ...
    def WriteInfo(self, builder: StringBuilder) -> None: ...

